Disallow 2-digit years in SimpleDateFormat.
corda/openjdk pull request #15
Opened 2017-09-11 15:30 UTC by chrisr3

When parsing dates with two-digit years, Java's default assumption is that the range 00 - 99 should be divided such that 20 are in the future and the remaining 80 are in the past. This division obviously changes year by year, and so cannot be allowed in a deterministic JVM.

2017-09-11 15:41 UTC, chrisr3 commented
This PR depends on the removal of `java.net.HttpCookie` and all of its friends.

2017-10-13 11:03 UTC, exFalso requested changes
I don't think this should be changed, the distinction *is* deterministic, the "current datetime" itself isnt.

2017-10-13 11:20 UTC, chrisr3 commented
This is _not_ deterministic. Java will map the same two-digit year into two totally different centuries as time progresses! The fact that Java needs to initialise its default century from the system clock (c.f. building a seed for `Random`) is a bit of a giveaway.

2017-10-13 11:56 UTC, exFalso commented
What I mean is it is the system clock's current time that's non-deterministic, not the branching in this code.
So in general we need to return a static date or remove the concept current time completely instead.

2017-10-13 13:38 UTC, chrisr3 commented
But it _does_ "remove the concept of current time", doesn't it? The default century is no longer being initialised to the system clock by default, which means that there no longer is a default century. Hence we cannot support 2 digit years.
```diff
-    private void initializeDefaultCentury() {
-        calendar.setTimeInMillis(System.currentTimeMillis());
-        calendar.add( Calendar.YEAR, -80 );
-        parseAmbiguousDatesAsAfter(calendar.getTime());
-    }
```

2017-10-13 14:26 UTC, exFalso approved these changes
Makes sense.
LGTM 👍

2017-10-13 14:48 UTC, merged