Chrisr3 files and network
corda/openjdk pull request #25
Opened 2017-10-20 16:10 UTC by chrisr3

Remove `java.nio.file.Files` and simplify `java.io.File`.
Remove `java.io.RandomAccessFile`.
Remove native `net` and `nio` libraries.
Remove `Channel` and `Selector` classes.
Remove network cookie, socket and interface classes.
Remove `javax.net.ssl` package.
Remove `com.sun.nio.sctp` package.
Remove `com.sun.org.apache.xml.internal.security` package.
Remove `com.sun.security.auth.PolicyFile`.
Remove `com.sun.security.ntlm` package.
Remove `sun.security.provider.certpath.ssl` package.
Remove `sun.net.smtp` package.
Remove `sun.net.spi` package.
Remove `sun.jvmstat.perfdata` package.

2017-10-25 10:09 UTC, tlil requested changes
Just a couple of minor comments, apart from that LGTM.

I noticed that some of the stuff in the `java.net` namespace is only partially taken out and some of it stubbed out. Do we want to look through that a bit more and see if we can strip out more?

2017-10-25 10:09 UTC, tlil commented on jdk/src/share/classes/com/sun/crypto/provider/KeyProtector.java
> +        cipher.init(Cipher.ENCRYPT_MODE, sKey, pbeSpec, null);
So this is to avoid it falling back to using `JceSecurity.RANDOM` for the `random` parameter, which is the default value in `init(opmode, key, params, random=JceSecurity.RANDOM);`

Would it be worth adding a comment here just to clarify?

2017-10-25 10:09 UTC, tlil commented on jdk/src/share/classes/com/sun/crypto/provider/KeyProtector.java
> +            cipher.init(Cipher.DECRYPT_MODE, skey, params, null);
Same as above re default parameter.

2017-10-25 10:17 UTC, tlil approved these changes

2017-10-25 10:17 UTC, tlil commented
I've added the comments that I requested. Re pruning `java.net` further, _if_ we want to do that, we can cover it in a follow-up PR.

2017-10-27 08:39 UTC, chrisr3 commented
This has always been an incremental process. The cut-off point for each of these PRs is when I have managed to get the following command to complete successfully:
```bash
$ make images docs
```

2017-10-27 08:39 UTC, merged

2017-10-27 08:57 UTC, tlil commented
Coolio, makes sense @chrisr3